### ISSUE TITLE
Not running on test dataset

### ISSUE THREAD

**Issue by elbourret** [johnssproul/RepeatProfiler#11]
I did a manual installation on my cluster (RepeatProfiler v 1.1 x Samurai x). The bin seems to be running fine. However, I run into two separate problems on my data, and also on the test dataset provided on this github page.
1. RepeatProfiler seems to be looking for `fasta_splitter.sh` in the wrong place. It always looks in the folder ./script within the current working directory, instead of the \<path to RepeatProfiler folder\>/script. Therefore, I can only run RepeatProfiler inside the same directory as the bin file.
2. When I do run within the RepeatProfiler folder, it goes through the indexing of the reference file, and then fails when checking the read files. For instance, if I run the below command:
```bash
WD=/home/bourret/progs/RepeatProfiler/sample_data
module load samtools bowtie2
module load gcc/10.3.0 r/4.1.2
export R_LIBS=~/R/$EBVERSIONR/
cd /home/bourret/progs/RepeatProfiler
../repeatprof profile \
    -p $WD/reference.fa \
    -o $WD \
    -t 1 \
    -indel 0.1 \
    $WD
```

It will fail with this error: `The path to the paired reads file(s) is incorrect, or the file(s) is/are in a unsupported format
Make sure the path is correct (note: there should be no spaces in folder/file names). Make sure read files have '.fastq' or '.fq' extensions. Compressed (i.e., '.gz') formats also accepted (e.g., 'fastq.gz').`

All the fastq files from the test dataset are placed directly within `/home/bourret/progs/RepeatProfiler/sample_data`, so this appears to be a bug.

**Comment by HounerX** [comment]
Hello, 
        I think The command structure has a problem  you should provide the full path of the reads right after the reference like 


try this 

`../repeatprof profile -p /home/bourret/progs/RepeatProfiler/sample_data/reference.fa /home/bourret/progs/RepeatProfiler/sample_data/ 
`


Thank you so much let me know if it helped

**Comment by elbourret** [comment]
Problem solved by putting the command and options in the right order: `repeatprof profile -p <ref.fa> <path to reads> <additional options>`

Thanks for the quick response, and sorry for not reading the documentation more carefully! :)

**Comment by HounerX** [comment]
Great ! I am glad !

Have a nice year !
 thank you so much

**Comment by elbourret** [comment]
This solved my 2nd issue, but the 1st issue remains: repeatprofiler will only run if I create a symlink to the scripts/ folder in my working directory. This works:
```bash
WD=/home/bourret/progs/RepeatProfiler/sample_data
REPROF_SRC=/home/bourret/progs/RepeatProfiler

cd $WD
ln -s $REPROF_SRC/scripts .
$REPROF_SRC/repeatprof profile \
    -p $WD/reference.fa \
    $WD \
    -o $WD
```

I also found out that it will not accept gzipped files (fastq.gz), but does run on .fastq files.

Thank you, and have a nice year as well!

**Comment by HounerX** [comment]
Oh If you would like to run repeat profiler from any directory easily, I would  suggest installing it via homebrew as it handles sym links and put repeatprofiler in your path. 

However, I think you bring up a very good point. If you use the manual installation like you did, you can only run repeat profiler from the bin directory, However using -o you can direct the output anywhere you want giving a full path to a folder. We might update this in a future update. 


I am not sure why you cant use fastq.gz ? I see you are using -p which is paired did you have the correct naming format of _1.fastq.gz and _2.fastq.gz ?


Thank you so much

**Comment by elbourret** [comment]
I simply gzipped the test data, which produced files in this format: `Dsim_test_R2.fastq.gz`.

I have an unrelated question about the way variants are encoded in the phylip file. Should I send an email to John Sproul for this?

**Comment by HounerX** [comment]
oh so if you want to use .gz it has to be _1.fastq.gz and _2.fastq.gz.    _R1.fastq.gz and _R2.fastq.gz wont work sorry  because It is my fault I always forget to add it to the code.  If you are curious, it is line 26 and 28 in map_reads.sh. It is really a silly that I always forget to fix. Thank you for bringing it to  attention.  I will fix it. 


You can do that,  but you  can also open a new issue with your question, and I will close this one
