### ISSUE TITLE
R scripts are not running on MacOsX

### ISSUE THREAD

**Issue by filipevictoria** [johnssproul/RepeatProfiler#6]
Hi, first happy 2021 to everyone and may this year be more peaceful than the previous one.
I have a problem running RepeatProfile on my Macbook. R scripts (like ggplot2) do not run in the same analysis. I can only get the results of the mapping. Everything is normal on my lab server, but as I am at home office this week I wanted to advance some analysis and unfortunately it didn't work out very well. Could you shed some light on that? Are my R packages on the macbook not being recognized by the RepeatProfile pipeline? I don't know .... I hope you can help me.

**Comment by HounerX** [comment]
Hello, 
         I hope you have a great year. Are you using the GitHub installation ? If yes did you run the command to install the R packages (if you had them it should recognize that). If you use the GitHub installation. It normally looks for R that you use in your path. 

This command i mean 

`echo "install.packages(c('ggplot2','ggpubr','scales','reshape2','png'), repos=\"https://cran.rstudio.com\")" | R --no-save
`

**Comment by filipevictoria** [comment]
Hi, first of all thanks for your reply.

No I used the installation by homebrew .... did it affect the process ???

**Comment by HounerX** [comment]
Oh thanks. I found a bug that I Introduced in the homebrew installation last time we update homebrew.  I will fix it in like an hour, and update you. 

Thank you



The git clone is working .

you can try to clone the repository and  install the R packages and also the dependencies 

you can install the dependencies like parallel,bowtie2,etc   package through homebrew

**Comment by filipevictoria** [comment]
Thanks....I will try git clone....

**Comment by HounerX** [comment]
Can you try `brew upgrade repeatprof`.  I think I fixed it in the new version. Let me know if you have any issues.

**Comment by filipevictoria** [comment]
Hi ... it's running smoothly now ...

Thank you very much

**Comment by HounerX** [comment]
I am really glad that you brought it up, and it is working now.. Feel free if to open a new issue if something comes up.

Good luck ! Have a good one !
