### ISSUE TITLE
Repeatprof profile error

### ISSUE THREAD

**Issue by mdgn15** [johnssproul/RepeatProfiler#8]
Hello,

First of all, thank you for the nice software! Sadly, I am getting an error when I try to use it

> done
> mapped reads
> analyzing reference: Idahao_CL1_5_3_179bp
> parallel [OPTIONS] command -- arguments
> 	for each argument, run command with argument, in parallel
> parallel [OPTIONS] -- commands
> 	run specified commands in parallel
> parallel: invalid option -- '-'
> [1] "running depth_analyser"
> Error in `$<-.data.frame`(`*tmp*`, Ref.Length, value = NA) : 
>   replacement has 1 row, data has 0
> Calls: $<- -> $<-.data.frame
> Execution halted
> /software/repeatprofiler/1.1/repeatprof: line 924: fofn_bam.txt: No such file or directory
> Thenumber: 
> false
> Saving color plots scaled across all references (horizontal gradient)... 
> Error in if (scale_value > 1 || scale_value <= 0) { : 
>   missing value where TRUE/FALSE needed
> Execution halted
> mv: cannot stat '*_tempi': No such file or directory
> ________________________________
> < The analysis has been completed! >

I am trying it both in my local pc and a supercomputer grid but both resulting with this error. I also want to point out that initially in my local pc I managed to run it without problems (with out of date curl errors), but somehow after sometime passed now it is giving the error above. 

Can you help me out with this?

Thanks

**Comment by HounerX** [comment]
Hello, Thank you for using the software.  I think the issue might be with your parallel dependency. Have you updated it or changed it recently ?

**Comment by mdgn15** [comment]
For my local pc I didn't updated any dependencies, for the supercomputer grid the admins installed it last week when I asked them. Both ways, do you have an idea how to solve it? I am not too experienced with informatics so I can't think of anything other than a new installation.

**Comment by mdgn15** [comment]
Ok I understood what you meant by parallel dependency. I thought you were referring to 'any' dependencies working in parallel.:) Found the correct parallel version now it works. Thanks!

**Comment by HounerX** [comment]
That's great to hear !
