### ISSUE TITLE
This program is Drosophila genomes only?

### ISSUE THREAD

**Issue by Kur1sutaru** [johnssproul/RepeatProfiler#9]
Can I use RepeatProfiler with a genome of a wide range of mammals, including humans?

**Comment by HounerX** [comment]
Hello, 
       Thank you for your question. Yes, you can use it. You can provide short-read data from any organism and reference sequences from your repeats of interest.  In our paper, we have analyzed repeats in  Tomatoes too not only drosophila. 


Thank you so much

**Comment by Kur1sutaru** [comment]
Thks guys! 😄
